/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTypeahead: typeof import('./src/components/AppTypeahead.vue')['default']
    AppTypeaheadCustom: typeof import('./src/components/AppTypeaheadCustom.vue')['default']
    AwarenessCamp: typeof import('./src/components/icons/AwarenessCamp.vue')['default']
    BackButton: typeof import('./src/components/icons/BackButton.vue')['default']
    BasketsIcon: typeof import('./src/components/icons/BasketsIcon.vue')['default']
    Beneficiary: typeof import('./src/components/icons/Beneficiary.vue')['default']
    BottomTabs: typeof import('./src/components/core/BottomTabs.vue')['default']
    Buying: typeof import('./src/components/icons/Buying.vue')['default']
    Dashboard: typeof import('./src/components/icons/Dashboard.vue')['default']
    Document: typeof import('./src/components/icons/Document.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    MediaIcon: typeof import('./src/components/icons/MediaIcon.vue')['default']
    MemoIcon: typeof import('./src/components/icons/MemoIcon.vue')['default']
    NewTicket: typeof import('./src/components/icons/NewTicket.vue')['default']
    PalletsIcon: typeof import('./src/components/icons/PalletsIcon.vue')['default']
    PhotoAttach: typeof import('./src/components/PhotoAttach.vue')['default']
    Profile: typeof import('./src/components/icons/Profile.vue')['default']
    Rescue: typeof import('./src/components/icons/Rescue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selling: typeof import('./src/components/icons/Selling.vue')['default']
    Ticket: typeof import('./src/components/icons/Ticket.vue')['default']
  }
}
